### ISSUE TITLE
Catalyst

### ISSUE THREAD

**Issue by Scitator** [vitrioil/Speech-Separation#1]
Hi,
Really nice project!
Would you like to tell more about your project?

Please, join our slack,
https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw

**Comment by vitrioil** [comment]
Hey,

Our project is basically separating speech of individual speakers from a video using both audio and visual features. So, if a user selects a person in a video, the network should be able to separate out the individual's speech.
This isn't our research, just an implementation of the paper [Looking to Listen at a Cocktail Party](https://arxiv.org/abs/1804.03619) and we used Pytorch+Catalyst for it and I have to say I was really bored to write the loops again and again so we chose Catalyst. I actually found out about catalyst from Kaggle. Really nice framework!

Thank you.
